services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: packto_api
    ports:
      - "8010:8010"
    environment:
      - DATABASE_URL=postgresql://postgres:[REDACTED]@db:5432/packto_db
      - MISTRAL_API_KEY=[REDACTED]
      - HF_API_KEY=***REMOVED***
      - GOOGLE_API_KEY=[REDACTED]
      - OPENAI_API_KEY=[REDACTED]
      - LANGCHAIN_API_KEY=[REDACTED]
    depends_on:
      db:
        condition: service_healthy
    restart: always
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./vectorstores:/app/vectorstores
      - ./src:/app/src
      - ./tools:/app/tools
      - ./NetworkProtocols:/app/NetworkProtocols
      - ./SplitDocumentation:/app/SplitDocumentation
    networks:
      - packto_network

  static-server:
    build:
      context: ./static_files
      dockerfile: Dockerfile
    container_name: static-server
    ports:
      - "8009:8009"
    networks:
      - packto_network

  db:
    image: postgres:latest
    container_name: packto_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: [REDACTED]
      POSTGRES_DB: packto_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - packto_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  db_data:

networks:
  packto_network:
    driver: bridge